/**
 * This Code is Open Source and distributed under a
 * Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License
 * (http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_GB)
 */
// Created @ 26 Dec 2012
package vazkii.tinkerer.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * ModelElementalDesk
 *
 * The Model for the Elemental Desk Block (Generated by techne)
 *
 * @author Vazkii
 */
public class ModelElementalDesk extends ModelBase {

	ModelRenderer Leg1,
				  Leg2,
				  Leg3,
				  Leg4,
				  Top,
				  LegEnd1,
				  LegEnd2,
				  LegEnd3,
				  LegEnd4,
				  Receptacle1,
				  Receptacle2,
				  InterLeg4,
				  Receptacle3,
				  Receptacle4,
				  InterLeg1,
				  InterLeg2,
				  InterLeg3,
				  Shape1;
  
  public ModelElementalDesk(){
	  textureWidth = 64;
	  textureHeight = 32;
    
      Leg1 = new ModelRenderer(this, 26, 17);
      Leg1.addBox(0F, 0F, 0F, 2, 6, 2);
      Leg1.setRotationPoint(3F, 17F, -5F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      Leg2 = new ModelRenderer(this, 26, 17);
      Leg2.addBox(0F, 0F, 0F, 2, 6, 2);
      Leg2.setRotationPoint(3F, 17F, 3F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      Leg3 = new ModelRenderer(this, 26, 17);
      Leg3.addBox(0F, 0F, 0F, 2, 6, 2);
      Leg3.setRotationPoint(-5F, 17F, -5F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      Leg4 = new ModelRenderer(this, 26, 17);
      Leg4.addBox(0F, 0F, 0F, 2, 6, 2);
      Leg4.setRotationPoint(-5F, 17F, 3F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(0F, 0F, 0F, 14, 3, 14);
      Top.setRotationPoint(-7F, 14F, -7F);
      Top.setTextureSize(64, 32);
      Top.mirror = true;
      LegEnd1 = new ModelRenderer(this, 0, 17);
      LegEnd1.addBox(0F, 0F, 0F, 4, 1, 4);
      LegEnd1.setRotationPoint(2F, 23F, -6F);
      LegEnd1.setTextureSize(64, 32);
      LegEnd1.mirror = true;
      LegEnd2 = new ModelRenderer(this, 0, 17);
      LegEnd2.addBox(0F, 0F, 0F, 4, 1, 4);
      LegEnd2.setRotationPoint(-6F, 23F, 2F);
      LegEnd2.setTextureSize(64, 32);
      LegEnd2.mirror = true;
      LegEnd3 = new ModelRenderer(this, 0, 17);
      LegEnd3.addBox(0F, 0F, 0F, 4, 1, 4);
      LegEnd3.setRotationPoint(-6F, 23F, -6F);
      LegEnd3.setTextureSize(64, 32);
      LegEnd3.mirror = true;
      LegEnd4 = new ModelRenderer(this, 0, 17);
      LegEnd4.addBox(0F, 0F, 0F, 4, 1, 4);
      LegEnd4.setRotationPoint(2F, 23F, 2F);
      LegEnd4.setTextureSize(64, 32);
      LegEnd4.mirror = true;
      Receptacle1 = new ModelRenderer(this, 17, 17);
      Receptacle1.addBox(0F, 0F, 0F, 2, 2, 2);
      Receptacle1.setRotationPoint(4F, 12F, 4F);
      Receptacle1.setTextureSize(64, 32);
      Receptacle1.mirror = true;
      Receptacle2 = new ModelRenderer(this, 17, 17);
      Receptacle2.addBox(0F, 0F, 0F, 2, 2, 2);
      Receptacle2.setRotationPoint(-3F, 12F, 4F);
      Receptacle2.setTextureSize(64, 32);
      Receptacle2.mirror = true;
      InterLeg4 = new ModelRenderer(this, 35, 17);
      InterLeg4.addBox(0F, 0F, 0F, 6, 1, 1);
      InterLeg4.setRotationPoint(-3F, 20.5F, -4.5F);
      InterLeg4.setTextureSize(64, 32);
      InterLeg4.mirror = true;
      Receptacle3 = new ModelRenderer(this, 17, 17);
      Receptacle3.addBox(0F, 0F, 0F, 2, 2, 2);
      Receptacle3.setRotationPoint(1F, 12F, 4F);
      Receptacle3.setTextureSize(64, 32);
      Receptacle3.mirror = true;
      Receptacle4 = new ModelRenderer(this, 17, 17);
      Receptacle4.addBox(0F, 0F, 0F, 2, 2, 2);
      Receptacle4.setRotationPoint(-6F, 12F, 4F);
      Receptacle4.setTextureSize(64, 32);
      Receptacle4.mirror = true;
      InterLeg1 = new ModelRenderer(this, 35, 17);
      InterLeg1.addBox(-4.5F, 20.5F, -3F, 1, 1, 6);
      InterLeg1.setRotationPoint(0F, 0F, 0F);
      InterLeg1.setTextureSize(64, 32);
      InterLeg1.mirror = true;
      InterLeg2 = new ModelRenderer(this, 35, 17);
      InterLeg2.addBox(0F, 20.5F, 0F, 1, 1, 6);
      InterLeg2.setRotationPoint(3.5F, 0F, -3F);
      InterLeg2.setTextureSize(64, 32);
      InterLeg2.mirror = true;
      InterLeg3 = new ModelRenderer(this, 35, 17);
      InterLeg3.addBox(0F, 0F, 0F, 6, 1, 1);
      InterLeg3.setRotationPoint(-3F, 20.5F, 3.5F);
      InterLeg3.setTextureSize(64, 32);
      InterLeg3.mirror = true;
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
  }

}
