/**
 * This Code is Open Source and distributed under a
 * Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License
 * (http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_GB)
 */
// Created @ 13 Jan 2012
package vazkii.tinkerer.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import vazkii.tinkerer.reference.MiscReference;

/**
 * ModelElementalDesk
 *
 * The Model for the Catalyst Capsule Blocks (Generated by techne)
 *
 * @author Vazkii
 */
public class ModelCatalystCapsule extends ModelBase {

	public static final ModelCatalystCapsule INSTANCE = new ModelCatalystCapsule();

    ModelRenderer MainTube,
    			  TopVertTube,
    			  TopHorizTube,
    			  BottomVertTube,
    			  BottomHorizTube;

    private ModelCatalystCapsule() {
    	textureWidth = 64;
    	textureHeight = 32;

    	MainTube = new ModelRenderer(this, 0, 0);
    	MainTube.addBox(0F, 0F, 0F, 4, 12, 4);
      	MainTube.setRotationPoint(-3F, 12F, -2F);
      	MainTube.setTextureSize(64, 32);
      	MainTube.mirror = true;
      	TopVertTube = new ModelRenderer(this, 16, 0);
      	TopVertTube.addBox(0F, 0F, 0F, 2, 3, 2);
      	TopVertTube.setRotationPoint(-2F, 9F, -1F);
      	TopVertTube.setTextureSize(64, 32);
      	TopVertTube.mirror = true;
      	TopHorizTube = new ModelRenderer(this, 24, 0);
      	TopHorizTube.addBox(0F, 0F, 0F, 5, 2, 2);
      	TopHorizTube.setRotationPoint(0F, 9F, -1F);
      	TopHorizTube.setTextureSize(64, 32);
      	TopHorizTube.mirror = true;
      	BottomVertTube = new ModelRenderer(this, 16, 5);
      	BottomVertTube.addBox(0F, 0F, 0F, 2, 8, 2);
      	BottomVertTube.setRotationPoint(3F, 11F, -1F);
      	BottomVertTube.setTextureSize(64, 32);
      	BottomVertTube.mirror = true;
      	BottomHorizTube = new ModelRenderer(this, 24, 5);
      	BottomHorizTube.addBox(0F, 0F, 0F, 5, 2, 2);
      	BottomHorizTube.setRotationPoint(3F, 19F, -1F);
      	BottomHorizTube.setTextureSize(64, 32);
      	BottomHorizTube.mirror = true;
    }

    /** Renders the model, must be translated previously **/
    public void render() {
    	MainTube.render(MiscReference.MODEL_DEFAULT_RENDER_SCALE);
    	TopVertTube.render(MiscReference.MODEL_DEFAULT_RENDER_SCALE);
    	TopHorizTube.render(MiscReference.MODEL_DEFAULT_RENDER_SCALE);
    	BottomVertTube.render(MiscReference.MODEL_DEFAULT_RENDER_SCALE);
    	BottomHorizTube.render(MiscReference.MODEL_DEFAULT_RENDER_SCALE);
    }
}
